receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  memory_limiter:
    limit_mib: 256
    check_interval: 1s
  
  # Add resource attributes
  resource:
    attributes:
      - key: deployment.environment
        value: demo
        action: upsert
      - key: service.namespace
        value: stood
        action: upsert

exporters:
  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: stood
    const_labels:
      environment: demo
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  
  # OTLP exporter for Jaeger traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Debug exporter for debugging
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200


extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/jaeger, debug]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [debug]
  
  telemetry:
    logs:
      level: "debug"
