#!/bin/bash
# Docker setup guide for AWS Documentation MCP Server with Stood (NEW Simple Method)
set -e

echo "🐳 AWS Documentation MCP Server Docker Setup Guide (NEW Simple Method)"
echo "======================================================================"
echo ""
echo "This example demonstrates the NEW simple MCP integration using with_mcp_client()!"
echo ""
echo "❗ IMPORTANT: The pre-built Docker image is not available in Docker Hub."
echo "   You need to build the Docker image from source first."
echo ""
echo "📋 Manual Setup Steps Required:"
echo ""
echo "1️⃣  Clone the MCP repository:"
echo "   git clone https://github.com/awslabs/mcp.git"
echo ""
echo "2️⃣  Navigate to the AWS Documentation MCP server directory:"
echo "   cd mcp/src/aws-documentation-mcp-server/"
echo ""
echo "3️⃣  Build the Docker image:"
echo "   docker build -t awslabs/aws-documentation-mcp-server ."
echo ""
echo "4️⃣  Verify the image was built successfully:"
echo "   docker images | grep awslabs/aws-documentation-mcp-server"
echo ""
echo "5️⃣  Return to this directory and run the example:"
echo "   cd examples/022_aws_doc_mcp"
echo "   cargo run --example 022_aws_doc_mcp"
echo ""
echo "⚠️  Note: Building the Docker image may take several minutes depending on"
echo "   your internet connection and system performance."
echo ""
echo "🔍 To check if you already have the image built:"
if docker images | grep -q awslabs/aws-documentation-mcp-server; then
    echo "✅ Found existing Docker image:"
    docker images | grep awslabs/aws-documentation-mcp-server
    echo ""
    echo "🚀 You can now run: cargo run --example 022_aws_doc_mcp"
else
    echo "❌ Docker image not found. Please follow the build steps above."
fi
echo ""
echo "💡 After building the image, the NEW Stood example will:"
echo "   ✅ Start the MCP server automatically using Docker"
echo "   ✅ Verify MCP tools work directly"
echo "   ✅ Create an agent using the simple with_mcp_client() method"
echo "   ✅ Demonstrate AWS documentation queries with tool verification"
echo ""
echo "📚 The server provides access to AWS documentation for CloudFormation, DynamoDB, SDKs, and more"
echo "🎯 Watch for 'SUCCESS: AWS Documentation MCP tools were called!' messages"